config/routes.rb
Rails.application.routes.draw do
  resources :article_categories

  resources :categories

  devise_for :users
  resources :articles
  resources :comments

  root 'articles#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :article
	belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	def create
		@comment = Comment.new(comment_params)
		@comment.user_id = current_user.id
		if @comment.save
		redirect_to article_path(@comment.article_id),notice: "Successfully added the comment"
		else
		render action :back 
		end
	end
	def show
		@comment = Comment.find(params[:id])
	end

	def destroy 
		@comments = Comment.find(params[:id])
		
			if @comments.destroy
				redirect_to :back,notice:"Comment deleted"
			end
	end 

	private
	def comment_params
	params[:comment].permit(:article_id,:title,:body,:user_id)
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/create.js.erb
var outerDiv = document.createElement('div');
var innerDiv = document.createElement('div');
outerDiv.setAttribute("class","media");
outerDiv.setAttribute("id","comment_<%=@comment.id %>");

innerDiv.setAttribute("class","media-left"); 

var img = document.createElement('img');
img.setAttribute("src","http://lorempixel.com/64/64/people/");
img.setAttribute("alt","Dummy image");
img.setAttribute("class","img-rounded");
innerDiv.appendChild(img);

var divMedia = document.createElement('div');
divMedia.setAttribute("class","media-body");

var header = document.createElement('h4');
header.setAttribute("class","media-heading");

var text = document.createTextNode("<%=@comment.title%>");
header.appendChild(text);

var body = document.createTextNode("<%=@comment.body%>");
divMedia.appendChild(header);
divMedia.appendChild(body);

var anchor = document.createElement('a');
anchor.setAttribute("data-confirm","Are you sure?");
anchor.setAttribute("class","btn btn-sm");
anchor.setAttribute("data-remote","true");
anchor.setAttribute("rel","nofollow");
anchor.setAttribute("data-method","delete");
anchor.setAttribute("href","/comments/<%=@comment.id%>");

var icon = document.createElement('i');
icon.setAttribute("class","glyphicon glyphicon-trash");

anchor.appendChild(icon);
divMedia.appendChild(anchor);

outerDiv.appendChild(innerDiv);
outerDiv.appendChild(divMedia);

$('#comments_section').append(outerDiv);
$('#comment_title').val("");
$('#comment_body').val("");

app/views/comments/destroy.js.erb
//var commentHandle = document.getElementById
$('#comment_<%= @comment.id %>').slideDown();

app/views/comments/new.html.erb
<h2>Here you can Comment </h2>

  <%= form_for @comment do |c| %>
 	
 	<%= c.article_id %>

    <%= c.user_id %>


   <%= c.label :comment %>
   <%= c.text_area :body %>



   <%= c.submit "submit" %>

 <% end %>

app/views/comments/show.html.erb
<% if @article.comments.empty? %> 
	<p> No Comments Found </p>
<% else %>
 	<% comments = @article.comments.all %>
 	<h4> Listing Comments </h4>
 	<ul>
 		<% comments.each do |comment| %>
 		 <li><%= comment.user.email %> </li><p><%= comment.title %> (<%= comment.body %>)
 		 <% if user_signed_in? %>
 				<% if comment.user.id == current_user.id %>
 				<%= link_to "Delete Comment" , comment_path(comment) ,method: :delete , data: {confirm: "Are You Sure?"} %> - <%= link_to "My comments" , comment_path(current_user) %></p>
 				<% end %></li>
 			<% end %>
 		<% end %>
 		</ul>
<% end %> 
	<%= form_for Comment.new do |f| %>
		<%= f.label :Leave_a_comment %> <br/>
		<%= f.text_field :title %> <br/>

		<%= f.label :Description %> <br/>
		<%= f.text_area :body %> <br/>
		
		<%= f.hidden_field :article_id , value: @article.id %> <br/>

		<%= f.submit "Add Comment" %>
	<% end %>