config/routes.rb
Rails.application.routes.draw do
  resources :article_categories

  resources :categories

  devise_for :users
  resources :articles
  resources :comments

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
	has_many :article_categories
	has_many :categories, through: :article_categories
	belongs_to :article
	belongs_to :category
	validates_presence_of :title,:body
	validates_length_of :body, minimum: 10
	validate :check_published_date
	private #Custom validations
	def check_published_date
		if self.published_date < Date.today  && self.published == false
			errors.add(:published_date,"cannot be greater than 1 month")
		end
	end

end

app/controllers/articles_controller.rb
 class ArticlesController < ApplicationController
 	before_action :authenticate_user!, except: [:index, :show]
 	  
 	  load_and_authorize_resource

	def index
	@articles = Article.paginate(:page => params[:page], :per_page => 2)
 
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		if @article .save
			redirect_to articles_path, notice: "successfully inserted"

		else
			render action: "new"
		end
	end

	def show
		category_ids=@article.categories.pluck(:id)
		selected_article_ids = ArticleCategory.where(category_id:category_ids).shuffle.first(2).map(&:article_id)
		@related_articles = Article.where(id: selected_article_ids)
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		if @article.update_attributes(article_params)
			redirect_to article_path(@article), notice: "successfully updated"
		else
			render action: "edit"
		end
    end

    def destroy
    	@article = Article.find(params[:id])
    	if @article.destroy
    		redirect_to articles_path, notice: "successfully deleted"
    	else
    		render action: back
    	end
	end

	private

	def article_params
		params[:article].permit(:title, :body, :published, :published_date, category_ids:[])
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<%= form_for @article do |f| %>
	<%= f.label :title, for: "title" %> <br/>
	<%= f.text_field :title,autofocus: true,id: "title" %> <br/>

<%= f.label :body %><br/>
<%= f.text_area :body,col:20,rows:5,id: "body" %> <br/>

<%= f.label :published %>	
<%= f.check_box :published %><br/>

<%= f.label :published_date %> </br>
<%= f.date_select :published_date,order: [:day,:month,:year] %> <br/>

<%= f.submit "Submit" %>
<% end %>

app/views/articles/index.html.erb
<div class="col-md-8">
 <% @articles.each do |article| %>
 <div class= "article_listing">
 <div class= "page-header">
 <h3><%= article.title%></h3>
 </div>
  <img src="http://lorempixel.com/600/250/nature/" alert="Dummy Image" class="Img-rounded">

  <%= article.body.truncate(300)%>
  <%= link_to "read more", article_path(article.id), class: "btn btn-info"%>
 </div>
  <hr/>
  <div class="pull-left">
   <b>Categories : </b>
    <%article.categories.each do |category|%>
    <%= link_to category.name, category %>
  <%end%>

 </div>

 <div class="pull-right">
    <i class="glyphicon glyphicon-time"></i> <%= article.published_date%>
 </div>
  <br/>
  <%end%>
  <%= will_paginate @articles %>
 </div>

 <div class="col-md-4">
   <div class="page-header">
   <h3>Categories</h3> 
 </div>
 <ul class="list-group">
 <% Category.all.each do |category|%>
  <li class="list-group-item">
   <span class="badge"><%= category.articles.size %></span>
    <%= link_to category.name, category %>
    </li>
    <%end%>
    </ul>
   </div>

app/views/articles/new.html.erb

<h2> Add new article</h2>

<%= form_for @article do |f| %>
<% if @article.errors.any? %>
		<h3>errors find</h3>
		<ul>
		<%= @article.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
		</ul>
<% end %>
	<%= f.label :title %>
	<%= f.text_field :title %></br>

	<%= f.label :body %>
	<%= f.text_area :body %></br>

	<%= f.label :published %>
	<%= f.check_box :published %> </br>

	<%= f.label :published_date %>
	<%= f.date_select :published_date %> </br>

	<%= f.label :select_categories %>
	<%= f.collection_check_boxes :category_ids, Category.all, :id, :name %> </br>

	<%= f.submit "Submit" %>
<% end %>



app/views/articles/show.html.erb
<p id="notice"><%=notice %></p>

<div class="col-md-8">
  <div class="page-header">
    <h2><%= @article.title %></h2>
  </div>  
  <img src="http://lorempixel.com/600/400/nature/" alt="Dummy Image" class="img-rounded"> <br>
  <p class="text-justify"><%= @article.body%></p>


  <hr/>
    <div class="pull-left">
      <b>Categories : </b>
      <% @article.categories.each do |category| %>
        <%= link_to category.name, category %>
      <% end %>
    </div>

    <div class="pull-right">
      <!-- <i class="glyphicon glyphicon-user"></i> <%# article.user.try(:username) %>  -->

      <i class="glyphicon glyphicon-time"></i> <%= @article.published_date %>
    </div>
    <br>
  <hr>


  <h4> Comments </h4>
  <div id="comments_section">
    <%@article.comments.each do |comment|%>

     <li>title:<%=comment.title%></li>
      body:<%= comment.body%><br/> 

      <div class="media" id="comment_<%= comment.id %>">
        <div class="media-left">
          <img class="media-object" src="http://lorempixel.com/64/64/people/">
        </div>

        <div class="media-body">
          <h4 class="media-heading"><%= comment.title%>
         <!-- <small><span class="pull-right"><%= comment.user.username%></span></small></h4> -->
          <%= comment.body%>
          <% if user_signed_in? && comment.user_id == current_user.id %>
      
            <%= link_to 'Delete comment',comment, method: :delete, data: { confirm: 'Are you sure?' }, remote: true ,class: "btn btn-danger" %> <br/><br/>
          <% end %>
        </div>
      </div>
    <%end%>
  </div>


     

 <% if user_signed_in? && current_user.is_admin %>
    <%= link_to "Edit", edit_article_path(@article) %>  | 
    <%= link_to "Destroy", article_path(@article), method: :delete, data:{confirm: "Are You Sure?"} %>  |  
  <% end %>

<%= link_to "Back", articles_path %>

<h3> Add comment </h3>
<div class ="well">
<%= form_for Comment.new ,remote: true do |f| %>
<div class ="form-group">
<label>Title</label>
<%= f.text_field :title,class: "form-control" %>
</div>
<div class ="form-group">
<label>Body</label>
<%= f.text_area :body,class: "form-control" %>
</div>
<%= f.hidden_field :article_id, value: @article.id %>
<%= f.submit "Add comment", class: "btn btn-primary" %>
<% end %>
</div>

<%#if can? :update, article %>
   <%# link_to "Edit", edit_article_path(@article) %>
  <%# end %>

<%#if can? :destroy, article %>
   <%# link_to "Destroy", article_path(@article), method: :delete, data:{confirm: "Are You Sure?"} %>
<%#end %> 

<!-- </div> -->

<div class="col-md-4">
  <div class="page-header">
    <h2>Related Articles</h2>
  </div>

  <% @related_articles.each do |article| %>
    <img src="http://lorempixel.com/250/100/nature/" alt="Dummy Image" class="img-rounded"> <br>
    <%= link_to article.title.truncate(50) , article %>
    <hr>
  <% end%>

  <div class="page-header">
    <h3>Categories</h3>
  </div>
  <ul class="list-groups">
    <% Category.all.each do |category| %>
      <li class="list-group-item">
        <span class="badge"> <%= category.articles.size %></span>
        <%= link_to category.name,category %>
      </li>
    <%end %>
  </ul>

</div>

