config/routes.rb
Rails.application.routes.draw do
  resources :article_categories

  resources :categories

  devise_for :users
  resources :articles
  resources :comments

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
	has_many :article_categories
	has_many :categories, through: :article_categories
	belongs_to :article
	belongs_to :category
	validates_presence_of :title,:body
	validates_length_of :body, minimum: 10
	validate :check_published_date
	private #Custom validations
	def check_published_date
		if self.published_date < Date.today  && self.published == false
			errors.add(:published_date,"cannot be greater than 1 month")
		end
	end

end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
	belongs_to :article
	belongs_to :category
end
	

app/controllers/article_categories_controller.rb
class ArticleCategoriesController < ApplicationController
  before_action :set_article_category, only: [:show, :edit, :update, :destroy]

  # GET /article_categories
  # GET /article_categories.json
  def index
    @article_categories = ArticleCategory.all
  end

  # GET /article_categories/1
  # GET /article_categories/1.json
  def show
  end

  # GET /article_categories/new
  def new
    @article_category = ArticleCategory.new
  end

  # GET /article_categories/1/edit
  def edit
  end

  # POST /article_categories
  # POST /article_categories.json
  def create
    @article_category = ArticleCategory.new(article_category_params)

    respond_to do |format|
      if @article_category.save
        format.html { redirect_to @article_category, notice: 'Article category was successfully created.' }
        format.json { render :show, status: :created, location: @article_category }
      else
        format.html { render :new }
        format.json { render json: @article_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /article_categories/1
  # PATCH/PUT /article_categories/1.json
  def update
    respond_to do |format|
      if @article_category.update(article_category_params)
        format.html { redirect_to @article_category, notice: 'Article category was successfully updated.' }
        format.json { render :show, status: :ok, location: @article_category }
      else
        format.html { render :edit }
        format.json { render json: @article_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /article_categories/1
  # DELETE /article_categories/1.json
  def destroy
    @article_category.destroy
    respond_to do |format|
      format.html { redirect_to article_categories_url, notice: 'Article category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article_category
      @article_category = ArticleCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_category_params
      params.require(:article_category).permit(:article_id, :category_id)
    end
end

app/helpers/article_categories_helper.rb
module ArticleCategoriesHelper
end

app/views/article_categories/_form.html.erb
<%= form_for(@article_category) do |f| %>
  <% if @article_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article_category.errors.count, "error") %> prohibited this article_category from being saved:</h2>

      <ul>
      <% @article_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :article_id %><br>
    <%= f.number_field :article_id %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :select_categories %><br>
    <%= f.collection_check_boxes :category_ids,Category.all, :id,:name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/article_categories/edit.html.erb
<h1>Editing article_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @article_category %> |
<%= link_to 'Back', article_categories_path %>

app/views/article_categories/index.html.erb
<h1>Listing article_categories</h1>

<table>
  <thead>
    <tr>
      <th>Article</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @article_categories.each do |article_category| %>
      <tr>
        <td><%= article_category.article_id %></td>
        <td><%= article_category.category_id %></td>
        <td><%= link_to 'Show', article_category %></td>
        <td><%= link_to 'Edit', edit_article_category_path(article_category) %></td>
        <td><%= link_to 'Destroy', article_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article category', new_article_category_path %>

app/views/article_categories/new.html.erb
<h1>New article_category</h1>

<%= render 'form' %>

<%= link_to 'Back', article_categories_path %>

app/views/article_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Article:</strong>
  <%= @article_category.article_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @article_category.category_id %>
</p>

<%= link_to 'Edit', edit_article_category_path(@article_category) %> |
<%= link_to 'Back', article_categories_path %>